name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed
  $CHANGES
categories:
  - title: ':boom: Breaking Changes'
    label: 'breaking change'
  - title: ':sparkles: Enhancements'
    label: 'enhancement'
  - title: ':bug: Bug Fixes'
    label: 'bug'
  - title: ':book: Documentation'
    label: 'documentation'

version-resolver:
  major:
    labels:
      - 'breaking change'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'documentation'

exclude-labels:
  - 'skip changelog'
