env:
  browser: true
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:jest-dom/recommended'
plugins:
  - prettier
  - import
  - jest-dom
ignorePatterns:
  - dist
  - node_modules
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
      - .tsx
  import/resolver:
    typescript:
      project:
        - tsconfig.json
        - '**/tsconfig.json'
    node: true
  import/internal-regex: ^src/
parserOptions:
  sourceType: module
rules:
  prettier/prettier: warn
  prefer-object-spread: warn
  prefer-spread: warn
  no-unused-expressions:
    - error
    - allowShortCircuit: true
      allowTernary: true
  no-useless-escape: 'off'
  camelcase:
    - warn
    - properties: never
  no-new: warn
  new-cap:
    - error
    - newIsCap: true
      capIsNew: false
  no-unused-vars:
    - error
    - varsIgnorePattern: ^_
      argsIgnorePattern: ^_
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  import/order:
    - error
    - newlines-between: always
      pathGroupsExcludedImportTypes: []
      groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
      alphabetize:
        order: asc
        caseInsensitive: true
overrides:
  - files:
      - '*.ts'
      - '*.tsx'
    parser: '@typescript-eslint/parser'
    extends:
      - 'plugin:@typescript-eslint/recommended'
      - prettier
    rules:
      '@typescript-eslint/no-var-requires': 'off'
      '@typescript-eslint/explicit-function-return-type': 'off'
      '@typescript-eslint/no-empty-interface': 'off'
      '@typescript-eslint/explicit-module-boundary-types': 'off'
      '@typescript-eslint/ban-types': warn
      no-empty-function: 'off'
      '@typescript-eslint/no-empty-function': 'off'
      camelcase: 'off'
      '@typescript-eslint/camelcase': 'off'
      no-use-before-define: 'off'
      '@typescript-eslint/no-use-before-define': 'off'
      '@typescript-eslint/prefer-namespace-keyword': 'off'
      '@typescript-eslint/no-unused-vars':
        - error
        - varsIgnorePattern: ^_
          argsIgnorePattern: ^_
  - files:
      - '*.spec.*'
      - '**/__tests__/**'
    env:
      node: true
      es6: true
      commonjs: true
      jest: true
  - files:
      - '*.config.js'
      - jest.setup.js
    env:
      node: true
      commonjs: true
      jest: true
