// This file was generated by RedwoodJS
import FatalErrorPageType from '/home/runner/work/create-jam/create-jam/app/jam-app/web/src/pages/FatalErrorPage/FatalErrorPage'
import NotFoundPageType from '/home/runner/work/create-jam/create-jam/app/jam-app/web/src/pages/NotFoundPage/NotFoundPage'

declare global {
  const FatalErrorPage: typeof FatalErrorPageType
  const NotFoundPage: typeof NotFoundPageType
}
