name: Create Redwood App
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  create_apps:
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        app:
          - "{ type: 'typescript', flags: '--typescript --no-yarn-install' }"
          - "{ type: 'javascript', flags: '--no-ts' }"
    uses: ./.github/workflows/create-app.yml
    with:
      name: redwood
      command: redwood-app
      type: ${{ fromJson(matrix.app).type }}
      flags: "--git false ${{ fromJson(matrix.app).flags }}"
      color: "bf4722"
