name: Create Eleventy App
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  create_apps:
    uses: ./.github/workflows/create-app.yml
    with:
      name: eleventy
      command: git clone
      git: "https://github.com/11ty/eleventy-base-blog.git"

  pr:
    needs: sort_common_files
    uses: ./.github/workflows/pr.yml
    with:
      name: eleventy
      command: git clone
      color: "000000"
