name: Create Eleventy App
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  create_apps:
    uses: ./.github/workflows/create-app.yml
    with:
      name: eleventy
      command: ""
      giget: "11ty/eleventy-base-blog#main"

  pr:
    needs: create_apps
    uses: ./.github/workflows/pr.yml
    with:
      name: eleventy
      command: giget
      color: "000000"
