name: Create Gatsby App
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  create_apps:
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        app:
          - "{ type: 'typescript', git: 'gatsby-starter-minimal-ts' }"
          - "{ type: 'javascript', git: 'gatsby-starter-minimal' }"
    uses: ./.github/workflows/create-app.yml
    with:
      name: gatsby
      command: ""
      giget: "gatsbyjs/${{ fromJson(matrix.app).git }}#master"
      type: ${{ fromJson(matrix.app).type }}

  pr:
    needs: create_apps
    uses: ./.github/workflows/pr.yml
    with:
      name: gatsby
      command: giget
      color: "663399"
