name: Create React App
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  create_apps:
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        app:
          - "{ type: 'typescript', flags: '--template typescript' }"
          - "{ type: 'javascript', flags: '' }"
    uses: ./.github/workflows/create-app.yml
    with:
      name: react
      command: react-app
      type: ${{ fromJson(matrix.app).type }}
      flags: "${{ fromJson(matrix.app).flags }}"
      color: 61dafb
