name: Create Docusaurus App
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  create_apps:
    strategy:
      fail-fast: false
      matrix:
        app:
          - "{ type: 'typescript', flags: '--typescript' }"
          - "{ type: 'javascript', flags: '' }"
    uses: spencerlabs/create-jam/.github/workflows/create-app.yml@next
    with:
      name: docusaurus
      command: docusaurus
      type: ${{ fromJson(matrix.app).type }}
      flags: "classic -s ${{ fromJson(matrix.app).flags }}"
      color: 3ECC5F
