name: Create Astro App
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  create_apps:
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        template:
          - basics
          - blog
          - minimal
    uses: ./.github/workflows/create-app.yml
    with:
      name: astro
      command: ""
      giget: "withastro/astro/examples/${{ matrix.template }}#latest"
      type: "${{ matrix.template }}"

  pr:
    needs: create_apps
    uses: ./.github/workflows/pr.yml
    with:
      name: astro
      command: giget
      color: 9333ea
