name: Create Docusaurus App
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  create_apps:
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        app:
          - "{ type: 'classic', append: '-ts', flags: '--typescript' }"
          - "{ type: 'classic', append: '-js', flags: '' }"
          - "{ type: 'facebook', append: '-js', flags: '' }"
    uses: ./.github/workflows/create-app.yml
    with:
      name: docusaurus
      command: docusaurus
      type: "${{ fromJson(matrix.app).type }}${{ fromJson(matrix.app).append }}"
      flags: "${{ fromJson(matrix.app).type }} -s ${{ fromJson(matrix.app).flags }}"
      color: 3ECC5F

  sort_common_files:
    needs: create_apps
    uses: ./.github/workflows/sort-common-files.yml
    with:
      app: docusaurus
