name: Create Hexo App
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  create_apps:
    uses: ./.github/workflows/create-app.yml
    with:
      name: hexo
      package: hexo-cli
      command: hexo init
      type: javascript

  sort_common_files:
    needs: create_apps
    uses: ./.github/workflows/sort-common-files.yml
    with:
      app: hexo

  pr:
    needs: sort_common_files
    uses: ./.github/workflows/pr.yml
    with:
      name: hexo
      command: hexo init
      cli: true
      color: 0D83CD
