name: Create Next.js App
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  create_apps:
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        app:
          - "{ type: 'typescript', flags: '--typescript' }"
          - "{ type: 'javascript', flags: '--javascript' }"
    uses: ./.github/workflows/create-app.yml
    with:
      name: next
      command: next-app
      type: ${{ fromJson(matrix.app).type }}
      flags: "--eslint ${{ fromJson(matrix.app).flags }}"

  sort_common_files:
    needs: create_apps
    uses: ./.github/workflows/sort-common-files.yml
    with:
      app: next

  pr:
    needs: sort_common_files
    uses: ./.github/workflows/pr.yml
    with:
      name: next
      command: next-app
      color: "000000"
