name: Create Nuxt App
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  create_apps:
    uses: ./.github/workflows/create-app.yml
    with:
      name: nuxt
      package: nuxi
      command: nuxi init

  pr:
    needs: create_apps
    uses: ./.github/workflows/pr.yml
    with:
      name: nuxt
      command: nuxi init
      cli: true
      color: 00dc82
